# Generated by Django 5.1.3 on 2024-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
