# Generated by Django 5.1.3 on 2024-11-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_cutom_last_na_723f5c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_last_na_2e448d_idx',
            old_name='store_cutom_last_na_723f5c_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
