# Generated by Django 5.1.3 on 2024-11-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_featured_products_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
