# Generated by Django 5.1.3 on 2024-11-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_quatity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
